BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (length(btrim(name)) > 0),
  email TEXT NOT NULL UNIQUE CHECK (length(btrim(email)) > 0),
  password_hash TEXT NOT NULL,
  phone TEXT UNIQUE,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'buyer'
    CHECK (role IN ('buyer', 'seller', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE CHECK (length(btrim(name)) > 0)
);

CREATE TABLE IF NOT EXISTS cars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  brand_id BIGINT NOT NULL REFERENCES brands(id) ON DELETE RESTRICT,
  model TEXT NOT NULL CHECK (length(btrim(model)) > 0),
  year INTEGER NOT NULL CHECK (year BETWEEN 1900 AND 2100),
  price NUMERIC(14, 2) NOT NULL CHECK (price > 0),
  mileage BIGINT NOT NULL CHECK (mileage >= 0),
  vehicle_condition TEXT NOT NULL
    CHECK (vehicle_condition IN ('new', 'used', 'certified')),
  fuel_type TEXT NOT NULL
    CHECK (fuel_type IN ('petrol', 'diesel', 'hybrid', 'electric')),
  transmission TEXT NOT NULL
    CHECK (transmission IN ('manual', 'automatic', 'cvt')),
  body_type TEXT,
  engine_size TEXT,
  color TEXT,
  city TEXT NOT NULL CHECK (length(btrim(city)) > 0),
  area TEXT NOT NULL CHECK (length(btrim(area)) > 0),
  description TEXT NOT NULL CHECK (length(btrim(description)) > 0),
  features TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'sold')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS car_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL CHECK (length(btrim(image_url)) > 0),
  public_id TEXT,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (car_id, sort_order)
);

ALTER TABLE car_images
  ADD COLUMN IF NOT EXISTS public_id TEXT,
  ADD COLUMN IF NOT EXISTS is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

UPDATE car_images AS image
SET is_primary = TRUE
WHERE image.id = (
  SELECT candidate.id
  FROM car_images AS candidate
  WHERE candidate.car_id = image.car_id
  ORDER BY candidate.sort_order, candidate.id
  LIMIT 1
)
AND NOT EXISTS (
  SELECT 1
  FROM car_images AS current_primary
  WHERE current_primary.car_id = image.car_id
    AND current_primary.is_primary
);

CREATE UNIQUE INDEX IF NOT EXISTS car_images_one_primary_per_car_idx
  ON car_images (car_id)
  WHERE is_primary;

CREATE TABLE IF NOT EXISTS favorites (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, car_id)
);

CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  car_id BIGINT REFERENCES cars(id) ON DELETE SET NULL,
  type TEXT NOT NULL CHECK (type IN ('contact', 'financing')),
  name TEXT NOT NULL CHECK (length(btrim(name)) > 0),
  email TEXT NOT NULL CHECK (length(btrim(email)) > 0),
  message TEXT NOT NULL CHECK (length(btrim(message)) > 0),
  status TEXT NOT NULL DEFAULT 'new'
    CHECK (status IN ('new', 'read', 'replied', 'closed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title TEXT,
  body TEXT NOT NULL CHECK (length(btrim(body)) > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, car_id)
);

CREATE INDEX IF NOT EXISTS cars_brand_status_idx ON cars (brand_id, status);
CREATE INDEX IF NOT EXISTS cars_status_created_at_idx ON cars (status, created_at DESC);
CREATE INDEX IF NOT EXISTS cars_city_idx ON cars (city);
CREATE INDEX IF NOT EXISTS inquiries_user_created_at_idx ON inquiries (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS inquiries_car_idx ON inquiries (car_id);
CREATE INDEX IF NOT EXISTS reviews_car_created_at_idx ON reviews (car_id, created_at DESC);

COMMIT;
